version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    command: CompileDaemon --build="go build -o backend ." --command="./backend"
