# Usar uma imagem base leve de Python
FROM python:3.9-slim

# Definir o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copiar somente os arquivos de dependências primeiro
COPY requirements.txt .

# Instalar as dependências necessárias
RUN pip install --no-cache-dir -r requirements.txt

# Copiar o restante do código para o contêiner
COPY . .

# Expor a porta 5000
EXPOSE 5000

# Comando para rodar a aplicação
CMD ["python", "ai_server.py"]
