basePath: /
definitions:
  models.CommitRequest:
    properties:
      commit_lang:
        type: string
      commit_length:
        enum:
        - short
        - long
        type: string
      commit_style:
        enum:
        - conventional
        - plain-text
        - emoji-style
        type: string
      model:
        type: string
      openai_key:
        type: string
      repo_path:
        type: string
    required:
    - commit_length
    - commit_style
    - model
    - repo_path
    type: object
  models.CommitResponse:
    properties:
      commit_message:
        type: string
      original_message:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: seu-email@dominio.com
    name: Seu Nome
    url: http://www.seu-site.com
  description: API para gerar mensagens de commit personalizadas usando IA.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Go Backend API
  version: "1.0"
paths:
  /generate-commit:
    post:
      consumes:
      - application/json
      description: Gera uma mensagem de commit personalizada usando IA
      parameters:
      - description: Dados para gerar o commit
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.CommitRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CommitResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Gera uma mensagem de commit
      tags:
      - Commit
  /health:
    get:
      consumes:
      - application/json
      description: Retorna o status de saúde do servidor
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Verifica o status do servidor
      tags:
      - Health
schemes:
- http
swagger: "2.0"
