basePath: /
definitions:
  handlers.ValidationError:
    properties:
      error:
        type: string
    type: object
  validation.ValidationResult:
    properties:
      currentBranch:
        type: string
      error:
        type: string
      isValid:
        type: boolean
      lastModified:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API para geração de commits, tradução e validação de repositórios.
  title: SmartCommit API
  version: "1.0"
paths:
  /validate:
    get:
      consumes:
      - application/json
      description: Verifica se o caminho fornecido é válido e contém um repositório
        Git
      parameters:
      - description: Caminho do repositório
        in: query
        name: path
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/validation.ValidationResult'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ValidationError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ValidationError'
      summary: Valida um repositório local
      tags:
      - Validation
swagger: "2.0"
