basePath: /
definitions:
  domain.Commit:
    properties:
      author:
        type: string
      config:
        $ref: '#/definitions/domain.CommitConfig'
      date:
        type: string
      message:
        type: string
    type: object
  domain.CommitConfig:
    properties:
      aiModel:
        type: string
      format:
        type: string
      language:
        type: string
      style:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server for generating commit messages using AI.
  title: Commit AI API
  version: "1.0"
paths:
  /ai-models:
    get:
      description: Obter uma lista de modelos de IA disponíveis para geração de commit
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: Obter modelos de IA disponíveis
  /commits:
    get:
      description: Obter todos os commits gerados
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Commit'
            type: array
      summary: Obter todos os commits
  /generate:
    post:
      consumes:
      - multipart/form-data
      description: Gerar uma mensagem de commit usando IA com configuração específica
        e arquivo README
      parameters:
      - description: Descrição do commit
        in: formData
        name: description
        required: true
        type: string
      - description: Autor do commit
        in: formData
        name: author
        required: true
        type: string
      - description: Formato do commit
        in: formData
        name: format
        required: true
        type: string
      - description: Arquivo README.md
        in: formData
        name: readmeFile
        required: true
        type: file
      - description: Modelo de IA
        in: formData
        name: aiModel
        required: true
        type: string
      - description: Estilo do commit
        in: formData
        name: style
        required: true
        type: string
      - description: Idioma do commit
        in: formData
        name: language
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Commit'
      summary: Gerar uma mensagem de commit
swagger: "2.0"
